[package]
name = "mirai"
version = "0.0.7"
edition = "2021"

[dependencies]
coloredpp = "0.3.0"
memmap2 = "0.9.5"
unicode-xid = "0.2.6"
smallvec = "1.13.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1